# Generated by Django 2.1.5 on 2019-01-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('detail', models.TextField()),
                ('category', models.CharField(choices=[('IT', 'IT'), ('teaching', 'Teaching'), ('banking', 'Banking'), ('marketing', 'Marketing')], default='IT', max_length=2)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
