# Generated by Django 2.1.5 on 2019-01-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20190106_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contact',
            field=models.CharField(default='000-0000000', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.CharField(default='abc@mail.com', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='islamabad', max_length=200),
        ),
    ]
